# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eTtuo9GbhaYCNwkrOQnDxaz_Xl53KPPp
"""

import socket

alvo = "scanme.nmap.org"   # alvo que permite testes

for porta in range(1, 101):
    s = socket.socket()
    s.settimeout(0.5)
    if s.connect_ex((alvo, porta)) == 0:
        print(f"Porta {porta} aberta")
    s.close()

print("Scan terminado")



import socket
from concurrent.futures import ThreadPoolExecutor

print("=== Scanner de portas simples ===")
print("Usa apenas em alvos autorizados (o teu PC ou scanme.nmap.org).\n")

alvo = input("Alvo (ex.: scanme.nmap.org): ").strip()

try:
    inicio = int(input("Porta inicial (ex.: 1): "))
    fim = int(input("Porta final (ex.: 1000): "))
except ValueError:
    print("Erro: as portas têm de ser números.")
    raise SystemExit

if not (1 <= inicio <= fim <= 65535):
    print("Erro: usa portas entre 1 e 65535, com inicial <= final.")
    raise SystemExit

try:
    ip = socket.gethostbyname(alvo)
except socket.gaierror:
    print("Erro: não foi possível resolver o alvo.")
    raise SystemExit


def testar_porta(porta):
    s = socket.socket()
    s.settimeout(0.5)
    try:
        if s.connect_ex((ip, porta)) == 0:
            return porta
    finally:
        s.close()
    return None


print(f"\nA fazer scan a {alvo} ({ip}), portas {inicio}-{fim}...\n")

with ThreadPoolExecutor(max_workers=50) as executor:
    resultados = executor.map(testar_porta, range(inicio, fim + 1))

abertas = [p for p in resultados if p is not None]

for p in abertas:
    print(f"Porta {p} aberta")

print(f"\nScan terminado. Portas abertas: {abertas if abertas else 'nenhuma'}")

import socket
from concurrent.futures import ThreadPoolExecutor

print("=== Scanner de portas simples ===")
print("Usa apenas em alvos autorizados (o teu PC ou scanme.nmap.org).\n")

alvo = input("Alvo (ex.: scanme.nmap.org): ").strip()

try:
    inicio = int(input("Porta inicial (ex.: 1): "))
    fim = int(input("Porta final (ex.: 1000): "))
except ValueError:
    print("Erro: as portas têm de ser números.")
    raise SystemExit

if not (1 <= inicio <= fim <= 65535):
    print("Erro: usa portas entre 1 e 65535, com inicial <= final.")
    raise SystemExit

try:
    ip = socket.gethostbyname(alvo)
except socket.gaierror:
    print("Erro: não foi possível resolver o alvo.")
    raise SystemExit


def testar_porta(porta):
    s = socket.socket()
    s.settimeout(0.5)
    try:
        if s.connect_ex((ip, porta)) == 0:
            return porta
    finally:
        s.close()
    return None


def nome_servico(porta):
    try:
        return socket.getservbyport(porta, "tcp")
    except OSError:
        return "desconhecido"


print(f"\nA fazer scan a {alvo} ({ip}), portas {inicio}-{fim}...\n")

with ThreadPoolExecutor(max_workers=50) as executor:
    resultados = executor.map(testar_porta, range(inicio, fim + 1))

abertas = [p for p in resultados if p is not None]

linhas = [f"Porta {p} aberta ({nome_servico(p)})" for p in abertas]

for linha in linhas:
    print(linha)

print(f"\nScan terminado. Portas abertas: {abertas if abertas else 'nenhuma'}")

with open("resultado_scan.txt", "w", encoding="utf-8") as f:
    f.write(f"Alvo: {alvo} ({ip})\n")
    f.write(f"Portas testadas: {inicio}-{fim}\n\n")
    f.write("\n".join(linhas) if linhas else "Nenhuma porta aberta")

print("Resultado guardado em resultado_scan.txt")